[tool.poetry]
name = "teledash"
version = "0.1.0"
description = ""
authors = ["labaffa <dellarovere.lante@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
telethon = "^1.28.5"
python-dotenv = "^1.0.0"
fastapi = "^0.97.0"
uvicorn = "^0.22.0"
jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
