"""empty message

Revision ID: 89f1764d89c5
Revises: 
Create Date: 2024-10-29 13:55:49.940198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '89f1764d89c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_client',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('active_collection',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), autoincrement=False, nullable=False),
    sa.Column('collection_title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'collection_title')
    )
    op.create_table('channel_collection',
    sa.Column('collection_title', sa.Text(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('channel_url', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('collection_title', 'user_id', 'channel_url')
    )
    op.create_table('channel_common',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('access_hash', sa.Integer(), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('url'),
    sa.UniqueConstraint('id', name='channel_id')
    )
    op.create_table('channel_custom',
    sa.Column('channel_url', sa.Text(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('is_joined', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('channel_url', 'user_id')
    )
    op.create_table('collection_job',
    sa.Column('uid', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('collection_title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('processed_channels', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'entity_type')
    )
    op.create_table('tg_client',
    sa.Column('id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('api_id', sa.Text(), nullable=True),
    sa.Column('api_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('displayname', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('salt', sa.Text(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='user_email')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('user_client',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_client')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tg_client')
    op.drop_table('entity')
    op.drop_table('collection_job')
    op.drop_table('channel_custom')
    op.drop_table('channel_common')
    op.drop_table('channel_collection')
    op.drop_table('active_collection')
    op.drop_table('active_client')
    # ### end Alembic commands ###
