"""create_non_fastapiusers_models

Revision ID: 9c3a81b3ce71
Revises: 
Create Date: 2024-03-18 19:18:46.801838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c3a81b3ce71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_client',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('active_collection',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('collection_title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'collection_title')
    )
    op.create_table('channel_collection',
    sa.Column('collection_title', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('collection_title', 'user_id', 'channel_url')
    )
    op.create_table('channel_common',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('access_hash', sa.Integer(), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=True),
    sa.Column('participants_count', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('url'),
    sa.UniqueConstraint('id', name='channel_id')
    )
    op.create_table('channel_custom',
    sa.Column('channel_url', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('is_joined', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('channel_url', 'user_id')
    )
    op.create_table('channel_tag',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'user_id', 'tag_id')
    )
    op.create_table('collection_job',
    sa.Column('uid', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('collection_title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('processed_channels', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'entity_type')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tg_client',
    sa.Column('id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('api_id', sa.Integer(), nullable=True),
    sa.Column('api_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('displayname', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='user_email'),
    sa.UniqueConstraint('username', name='user_username')
    )
    op.create_table('user_client',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_client')
    op.drop_table('user')
    op.drop_table('tg_client')
    op.drop_table('tag')
    op.drop_table('entity')
    op.drop_table('collection_job')
    op.drop_table('channel_tag')
    op.drop_table('channel_custom')
    op.drop_table('channel_common')
    op.drop_table('channel_collection')
    op.drop_table('active_collection')
    op.drop_table('active_client')
    # ### end Alembic commands ###
