"""empty message

Revision ID: b6e198d33eb5
Revises: 943caf599aa8
Create Date: 2024-08-20 12:20:51.092919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e198d33eb5'
down_revision: Union[str, None] = '943caf599aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('channel_tag')
    op.add_column('channel_collection', sa.Column('language', sa.Text(), nullable=True))
    op.add_column('channel_collection', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('channel_collection', sa.Column('category', sa.Text(), nullable=True))
    # op.create_unique_constraint('user_username', 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('user_username', 'user', type_='unique')
    op.drop_column('channel_collection', 'category')
    op.drop_column('channel_collection', 'location')
    op.drop_column('channel_collection', 'language')
    op.create_table('channel_tag',
    sa.Column('channel_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'user_id', 'tag_id')
    )
    op.create_table('tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
